name: Build, Publish, and Deploy

on:
  push:
    branches:
      - main
      - dev-Backend
  pull_request:
    branches:
      - main
      - dev-Backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tony203/iupi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --default-timeout=100 --no-cache-dir -r ./model-2/fintech_recommender/requirements.txt

      - name: Verify Django installation
        run: |
          python -m django --version 

      - name: Run migrations
        run: |
          python ./model-2/fintech_recommender/manage.py migrate  

      - name: Collect static files
        run: |
          python ./model-2/fintech_recommender/manage.py collectstatic --noinput  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest ./model-2/fintech_recommender 
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker Hub
        run: docker logout
